### ISSUE TITLE
1.21 Update

### ISSUE THREAD

**Issue by Jodekq** [JMReich/Path_To_Grass#1]
Any information on when you will update the mod to 1.21?

**Comment by JMReich** [comment]
Hi, thanks for your interest. I will start working on updating the mod today.

**Comment by JMReich** [comment]
The mod has been updated to 1.21 and it has been published on github and modrinth. 
I have also added support for off hand (left hand) use. 

Modrinth: https://modrinth.com/mod/path-to-grass/version/1.0.1+1.21

Thank you for waiting.
